# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Prifina' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Prifina
  pod 'Amplify'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
#  pod 'AmplifyPlugins/AWSAPIPlugin'
  pod 'ReachabilitySwift'
  pod 'SVProgressHUD'
  pod 'IQKeyboardManagerSwift'
  pod "Apollo"

  target 'PrifinaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PrifinaUITests' do
    # Pods for testing
  end

end
